#@ load("@ytt:data", "data")

apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: #@ "stack-" + data.values.USER_ID
spec:
  buildImage:
    image: registry.lab.livefire.dev/tbs/build-service/build@sha256:c484ec9919b724ee93bde4431fa79996e42c0bd1d5b69b78450e403451aaa615
  id: io.buildpacks.stacks.bionic
  runImage:
    image: registry.lab.livefire.dev/tbs/build-service/run@sha256:367a43536f60c21190cea5c06d040d01d29f4102840d6b3e1dcd72ed2eb71721
